python:
   version: 3.8
   install:
      - method: pip
        path: .
        extra_requirements:
           - doc
      - requirements: docs/requirements.txt
      - method: setuptools
        path: .
